version: "2"
services:
  web:
    container_name: api.pinpper.com
    build: .
    command: pm2-runtime process.json
    volumes:
      - .:/usr/api.pinpper.com
      - ./node_modules:/usr/api.pinpper.com/node_modules
      - ./public/uploads:/usr/api.pinpper.com/public/uploads
    ports:
      - "5000:5000"
    networks:
      - pinpper
    restart: always


networks: 
       pinpper:
          driver: bridge
