version: "2"
services:
  tesseract:
    container_name: tesseract
    build: .
    volumes:
      - .:/usr/tesseract
      - ./node_modules:/usr/tesseract/node_modules
      - ./public/uploads:/usr/tesseract/public/uploads
    ports:
      - "8888:8888"