apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-chegarapidoexpress-com
spec:
  selector:
    matchLabels:
      app: api-chegarapidoexpress-com
  replicas: 1
  template:
    metadata:
      labels:
        app: api-chegarapidoexpress-com
    spec:
      containers:
        - name: api-chegarapidoexpress-com
          image: despossivel/api.chegarapidoexpress.com:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: chegarapidoexpress-upload
              mountPath: /usr/src/app/public/uploads
      imagePullSecrets:
        - name: regcred


      volumes:
        - name: chegarapidoexpress-upload
          persistentVolumeClaim:
            claimName: chegarapidoexpress-upload
