apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pinpper-com
spec:
  selector:
    matchLabels:
      app: api-pinpper-com
  replicas: 1
  template:
    metadata:
      labels:
        app: api-pinpper-com
    spec:
      containers:
        - name: api-pinpper-com
          image: despossivel/api.pinpper.com
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
