apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tesseract-ocr-com
spec:
  selector:
    matchLabels:
      app: api-tesseract-ocr-com
  replicas: 1
  template:
    metadata:
      labels:
        app: api-tesseract-ocr-com
    spec:
      containers:
        - name: api-tesseract-ocr-com
          image: despossivel/api.tesseract-ocr.com:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: tesseract-ocr-upload
              mountPath: /usr/src/app/public/uploads
      imagePullSecrets:
        - name: regcred


      volumes:
        - name: tesseract-ocr-upload
          persistentVolumeClaim:
            claimName: tesseract-ocr-upload
