apiVersion: v1
kind: Service
metadata:
  name: api-chegarapidoexpress-com-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: api-chegarapidoexpress-com
