name: api.pinpper.com

on:
  push:
    - branches:
      - "master"

   steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd  ${{ secrets.DIR }}
            git pull
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY}}